jwt:
  secret: ${JWT_SECRET}
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/aipro?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

ai:
  uri: ${AI_URL}

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      file: ./compose-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  docker:
    compose:
      enabled: false
