jwt:
  secret: ${JWT_SECRET}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/aipro?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ai:
  uri: ${AI_URL}
